namespace:
  name: api

image:
  tag: latest
  repositories:
    redis: redis
    api: api

redis:
  port: 6379
  
api:
  host: ''
  port: 80
  yourModuleConnectionString: ''
  jwtSigningSecretKey: ''
  jwtEncryptionSecretKey: ''
