deploy:
  enabledServices:
    - api-internal
    - api-external
    - cache-redis
    - prometheus
    - grafana
    - zipkin

image:
  tag: latest
  repositories:
    apiInternal: api-internal
    apiExternal: api-external
    redis: redis
    prometheus: prometheus
    grafana: grafana
    zipkin: zipkin

services:
  apiInternal:
    internalPort: 443
    externalPort: 444
  apiExternal:
    internalPort: 443
    externalPort: 443
  redis:
    internalPort: 6379
    externalPort: 6379
  prometheus:
    internalPort: 9090
    externalPort: 9090
  grafana:
    internalPort: 3000
    externalPort: 3000
  zipkin:
    internalPort: 9411
    externalPort: 9411
