deploy:
  enabledServices: ""

image:
  tag: latest
  repositories:
    apiInternal: api-internal
    apiExternal: api-external
    grafana: grafana
    prometheus: prometheus
    zipkin: zipkin
    redis: redis

services:
  apiInternal:
    internalPort: 443
    externalPort: 444
  apiExternal:
    internalPort: 443
    externalPort: 443
  grafana:
    internalPort: 3000
    externalPort: 3000
  prometheus:
    internalPort: 9090
    externalPort: 9090
  zipkin:
    internalPort: 9411
    externalPort: 9411
  redis:
    internalPort: 6379
    externalPort: 6379