deploy:
  enabledServices:
    - api-internal
    - api-external
    - cache-redis
    - prometheus
    - grafana
    - zipkin

image:
  tag: latest
  repositories:
    apiInternal: api-internal
    apiExternal: api-external
    redis: redis
    prometheus: prometheus
    grafana: grafana
    zipkin: zipkin

services:
  apiInternal:
    port: 80
    dataSourceConnectionString: ""
    jwtSigningSecretKey: ""
    jwtEncryptionSecretKey: ""
    host: ""
  apiExternal:
    port: 80
    dataSourceConnectionString: ""
    jwtSigningSecretKey: ""
    jwtEncryptionSecretKey: ""
    host: ""
  redis:
    port: 6379
  prometheus:
    port: 9090
    host: ""
  grafana:
    port: 3000
    host: ""
    adminPassword: ""
  zipkin:
    port: 9411
    host: ""
  letsEncrypt:
    email: ""
  oauth2:
    port: 80
    host: ""
    hostRoot: ""
    clientIdGitHub: ""
    clientSecretGitHub: ""
    cookieSecret: ""
    emailDomainGitHub: ""
