namespace:
  name: api-internal

image:
  tag: latest
  repositories:
    redis: redis
    apiInternal: api-internal

redis:
  port: 6379
  
apiInternal:
  host: ''
  port: 80
  dataSourceConnectionString: ''
  jwtSigningSecretKey: ''
  jwtEncryptionSecretKey: ''
