apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-internal
  template:
    metadata:
      labels:
        app: api-internal
    spec:
      containers:
        - env:
          - name: ACR_LOGIN_SERVER
            valueFrom:
              secretKeyRef:
                key: login-server
                name: acr-secret
        - name: api-internal
          image: $ACR_LOGIN_SERVER/api-internal:latest
          ports:
            - containerPort: 443
          securityContext:
            allowPrivilegeEscalation: false