{{- if has "api-external" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Service
metadata:
  name: apiExternal
spec:
  selector:
    app: apiExternal
  ports:
    - port: {{ .Values.services.apiExternal.externalPort }}
      targetPort: {{ .Values.services.apiExternal.internalPort }}
{{- end }}
