{{- if has "api-external" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Service
metadata:
  name: api-external
spec:
  selector:
    app: api-external
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.apiExternal.port }}
      targetPort: {{ .Values.services.apiExternal.port }}
{{- end }}
