{{- if has "api-internal" .Values.deploy.enabledServices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-internal
  template:
    metadata:
      labels:
        app: api-internal
    spec:
      containers:
        - name: api-internal
          image: "{{ .Values.acrLoginServer }}/{{ .Values.image.repositories.api-internal }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.apiInternal.internalPort }}
          securityContext:
            allowPrivilegeEscalation: false
{{- end }}
