{{- if (has "api-internal" (splitList "," .Values.deploy.enabledServices)) }}
apiVersion: v1
kind: Service
metadata:
  name: apiInternal
spec:
  selector:
    app: apiInternal
  ports:
    - port: {{ .Values.services.apiInternal.externalPort }}
      targetPort: {{ .Values.services.apiInternal.internalPort }}
{{- end }}
