{{- if has "api-external" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Service
metadata:
  name: api-external
spec:
  selector:
    app: api-external
  type: LoadBalancer
  ports:
    - name: http
      nodePort: {{ .Values.services.apiExternal.externalPort }}
      port: {{ .Values.services.apiExternal.externalPort }}
      targetPort: {{ .Values.services.apiExternal.internalPort }}
{{- end }}
