{{- if has "api-internal" .Values.deploy.enabledServices }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-internal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.services.apiInternal.host }}
      secretName: api-internal-tls
  rules:
    - host: {{ .Values.services.apiInternal.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-internal
                port:
                  number: 80
{{- end }}
