{{- if has "api-internal" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Service
metadata:
  name: api-internal
spec:
  selector:
    app: api-internal
  type: LoadBalancer
  ports:
    - name: http
      nodePort: {{ .Values.services.api-internal.externalPort }}
      port: {{ .Values.services.api-internal.externalPort }}
      targetPort: {{ .Values.services.api-internal.internalPort }}
{{- end }}
