{{- if has "api-internal" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Service
metadata:
  name: api-internal
spec:
  selector:
    app: api-internal
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.apiInternal.externalPort }}
      targetPort: {{ .Values.services.apiInternal.internalPort }}
{{- end }}
