{{- if has "api-external" .Values.deploy.enabledServices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-external
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-external
  template:
    metadata:
      labels:
        app: api-external
    spec:
      containers:
        - name: api-external
          image: "{{ .Values.acrLoginServer }}/{{ .Values.image.repositories.apiExternal }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.apiExternal.port }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.services.apiExternal.port }}"
            - name: ConnectionStrings__DataSourceConnection
              valueFrom:
                secretKeyRef:
                  name: api-external
                  key: dataSourceConnectionString
            - name: AppSettings__JwtKeys__SigningSecretKey
              valueFrom:
                secretKeyRef:
                  name: api-external
                  key: jwtSigningSecretKey
            - name: AppSettings__JwtKeys__EncryptionSecretKey
              valueFrom:
                secretKeyRef:
                  name: api-external
                  key: jwtEncryptionSecretKey
{{- end }}
