{{- if has "grafana" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
type: Opaque
stringData:
  password: {{ .Values.services.grafana.adminPassword | quote }}
{{- end }}
