{{- if has "grafana" .Values.deploy.enabledServices }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: default
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.services.grafana.host }}
  dnsNames:
    - {{ .Values.services.grafana.host }}
{{- end }}