apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  ports:
    - port: {{ .Values.services.oauth2.port }}
      targetPort: {{ .Values.services.oauth2.port }}
  selector:
    app: oauth2-proxy