apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
stringData:
  client-id-github: {{ .Values.services.oauth2.clientIdGitHub | quote }}
  client-secret-github: {{ .Values.services.oauth2.clientSecretGitHub | quote }}
  cookie-secret: {{ .Values.services.oauth2.cookieSecret | quote }}
  email-domain-github: {{ .Values.services.oauth2.emailDomainGitHub | quote }}
