apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          name: oauth2-proxy
          args:
            - --provider=github
            - --client-id=$(CLIENT_ID_GITHUB)
            - --client-secret=$(CLIENT_SECRET_GITHUB)
            - --cookie-secret=$(COOKIE_SECRET)
            - --email-domain=$(EMAIL_DOMAIN_GITHUB)
            - --redirect-url=https://{{ .Values.services.oauth2.host }}/oauth2/callback            
            - --cookie-domain={{ .Values.services.oauth2.hostRoot }}
            - --whitelist-domain={{ .Values.services.oauth2.hostRoot }}
            - --reverse-proxy=true            
            - --set-authorization-header=true
            - --pass-authorization-header=true
            - --http-address=0.0.0.0:{{ .Values.services.oauth2.internalPort }}
            - --cookie-secure=true
            - --set-xauthrequest=true
          env:
            - name: CLIENT_ID_GITHUB
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: client-id-github
            - name: CLIENT_SECRET_GITHUB
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: client-secret-github
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: cookie-secret
            - name: EMAIL_DOMAIN_GITHUB
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: email-domain-github
          ports:
            - containerPort: {{ .Values.services.oauth2.internalPort }}
