apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth2-proxy-cert
  namespace: default
spec:
  secretName: oauth2-proxy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.services.oauth2.host }}
  dnsNames:
    - {{ .Values.services.oauth2.host }}
