{{- if has "prometheus" .Values.deploy.enabledServices }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.services.oauth2.host }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.services.oauth2.host }}/oauth2/start?rd=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, Set-Cookie, Authorization"
spec:
  tls:
    - hosts:
        - {{ .Values.services.prometheus.host }}
      secretName: prometheus-tls
  rules:
    - host: {{ .Values.services.prometheus.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: {{ .Values.services.prometheus.port }}
{{- end }}