{{- if has "zipkin" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  type: LoadBalancer
  ports:
    - name: http
      nodePort: {{ .Values.services.zipkin.externalPort }}
      port: {{ .Values.services.zipkin.externalPort }}
      targetPort: {{ .Values.services.zipkin.internalPort }}
{{- end }}
