{{- if has "zipkin" .Values.deploy.enabledServices }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-ingress-class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.services.oauth2.host }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.services.oauth2.host }}/oauth2/start?rd=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, Set-Cookie, Authorization"
spec:
  tls:
    - hosts:
        - {{ .Values.services.zipkin.host }}
      secretName: zipkin-tls
  rules:
    - host: {{ .Values.services.zipkin.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zipkin
                port:
                  number: {{ .Values.services.zipkin.port }}
{{- end }}