{{- if has "zipkin" .Values.deploy.enabledServices }}
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.zipkin.port }}
      targetPort: {{ .Values.services.zipkin.port }}
{{- end }}
