# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main", "v1.0", "v1.1"]
  pull_request:
    branches: ["main", "v1.0", "v1.1"]
  workflow_dispatch:

jobs:
  build-and-test:
    uses: build-and-test.yml
    with:
      solution: 'Deve.All.sln'
