# This workflow requires the environment production with the secrets used in the deploy-azure-aks.yml

name: Deploy All services to Production

on:
  push:
    branches:
      - production/all
    tags:
      - 'all/v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  checks:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      app_internal: ${{ steps.checks.outputs.app_internal }}
      app_external: ${{ steps.checks.outputs.app_external }}
      aks: ${{ steps.checks.outputs.aks }}
    steps:
      - name: Check secrets
        id: checks
        shell: bash        
        env:
          INTERNAL_SECRET: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_INTERNAL }}
          EXTERNAL_SECRET: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_EXTERNAL }}
          DEPLOY_TYPE: ${{ vars.DEPLOY_TYPE }}
        run: |
          app_internal=false
          app_external=false
          aks=false

          if [[ "$INTERNAL_SECRET" != "" && "$DEPLOY_TYPE" == "app" ]]; then
            app_internal=true
          fi
          if [[ "$EXTERNAL_SECRET" != "" && "$DEPLOY_TYPE" == "app" ]]; then
            app_external=true
          fi
          if [[ "$DEPLOY_TYPE" == "aks" ]]; then
            aks=true
          fi

          echo "app_internal=$app_internal" >> "$GITHUB_OUTPUT"
          echo "app_external=$app_external" >> "$GITHUB_OUTPUT"
          echo "aks=$aks" >> "$GITHUB_OUTPUT"
          
          echo "DEPLOY_TYPE=$DEPLOY_TYPE"
          echo "app_internal=$app_internal"
          echo "app_external=$app_external"
          echo "aks=$aks"
    
  build-and-test-api-internal:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution: "Deve.Api.Internal.sln"

  build-and-test-api-external:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution: "Deve.Api.External.sln"

  deploy-all-aks:
    if: ${{ needs.checks.outputs.aks == 'true' }}
    needs: [checks,build-and-test-api-internal,build-and-test-api-external]
    uses: ./.github/workflows/deploy-azure-aks.yml
    with:
      environment: "production"
      services: "api-internal,api-external,monitoring"
    secrets: inherit

  deploy-all-api-internal:
    if: ${{ needs.checks.outputs.app_internal == 'true' }}
    needs: [checks,build-and-test-api-internal]
    uses: ./.github/workflows/deploy-azure-app.yml
    with:
      environment: "production"
      project: "Internal/Api/Deve.Internal.Api.csproj"
      name: ${{ vars.AZURE_WEBAPP_NAME_INTERNAL }}
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_INTERNAL }}

  deploy-all-api-external:
    if: ${{ needs.checks.outputs.app_external == 'true' }}
    needs: [checks,build-and-test-api-external]
    uses: ./.github/workflows/deploy-azure-app.yml
    with:
      environment: "production"
      project: "External/Api/Deve.External.Api.csproj"
      name: ${{ vars.AZURE_WEBAPP_NAME_EXTERNAL }}
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_EXTERNAL }}
