# This workflow requires the environment production with the secrets used in the deploy-azure-aks.yml

name: Deploy All services to Production

on:
  push:
    branches:
      - production/all
    tags:
      - 'all/v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  checks:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      api: ${{ steps.checks.outputs.api }}
      aks: ${{ steps.checks.outputs.aks }}
    steps:
      - name: Check secrets
        id: checks
        shell: bash        
        env:
          API_SECRET: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          DEPLOY_TYPE: ${{ vars.DEPLOY_TYPE }}
        run: |
          api=false
          aks=false

          if [[ "$API_SECRET" != "" && "$DEPLOY_TYPE" == "api" ]]; then
            api=true
          fi
          if [[ "$DEPLOY_TYPE" == "aks" ]]; then
            aks=true
          fi

          echo "api=$api" >> "$GITHUB_OUTPUT"
          echo "aks=$aks" >> "$GITHUB_OUTPUT"
          
          echo "DEPLOY_TYPE=$DEPLOY_TYPE"
          echo "api=$api"
          echo "aks=$aks"
    
  build-and-test-api:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution: "Deve.Api.slnx"

  deploy-all-aks:
    if: ${{ needs.checks.outputs.aks == 'true' }}
    needs: [checks,build-and-test-api]
    uses: ./.github/workflows/deploy-azure-aks.yml
    with:
      environment: "production"
      services: "api,monitoring"
    secrets:
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      JWT_SIGNING_SECRET_KEY: ${{ secrets.JWT_SIGNING_SECRET_KEY }}
      JWT_ENCRYPTION_SECRET_KEY: ${{ secrets.JWT_ENCRYPTION_SECRET_KEY }}
      YOURMODULE_DATASOURCE_CONNECTIONSTRING: ${{ secrets.YOURMODULE_DATASOURCE_CONNECTIONSTRING }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      DB_USERS_PASSWORD: ${{ secrets.DB_USERS_PASSWORD }}
      KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
      SECRET_GRAFANA: ${{ secrets.SECRET_GRAFANA }}
      SECRET_PROMETHEUS: ${{ secrets.SECRET_PROMETHEUS }}
      SECRET_ZIPKIN: ${{ secrets.SECRET_ZIPKIN }}

  deploy-all-api:
    if: ${{ needs.checks.outputs.api == 'true' }}
    needs: [checks,build-and-test-api]
    uses: ./.github/workflows/deploy-azure-api.yml
    with:
      environment: "production"
      project: "Api/Deve.Api.csproj"
      name: ${{ vars.AZURE_WEBAPP_NAME }}
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
