# This workflow requires the environment production with the secrets used in the deploy-azure-aks.yml

name: Deploy All services to Production

on:
  push:
    branches:
      - production/all
    tags:
      - 'all/v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-test-api-internal:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution: "Deve.Api.Internal.sln"

  build-and-test-api-external:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution: "Deve.Api.External.sln"

  deploy-all:
    needs: [build-and-test-api-internal,build-and-test-api-external]
    uses: ./.github/workflows/deploy-azure-aks.yml
    with:
      environment: "production"
      services: "api-internal,api-external,monitoring"
    secrets: inherit
