# Based on the worflow available here: https://docs.github.com/en/actions/how-tos/deploy/deploy-to-third-party-platforms/net-to-azure-app-service
name: Build and deploy ASP.Net Core app to an Azure Web App

on:
  workflow_call:
    inputs:
      environment:
        description: "The GitHub environment used to get the secrets and vars needed"
        type: string
        required: true
      project:
        description: "The project to build and publish"
        type: string
        required: true
      name:
        description: "The name of the project"
        type: string
        required: true

    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

# Only allow one deploy per environment
concurrency: ${{ inputs.environment }}

jobs:
  build-azure-app:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0

      - name: Set up .NET Core
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d #v5.0.0
        with:
          dotnet-version: 9.0.x

      - name: Set up dependency caching for faster builds
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  #v4.3.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release ${{ inputs.project }}

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp ${{ inputs.project }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4  #v5.0.0
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-azure-app:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: build-azure-app

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53  #v6.0.0
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ inputs.name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/myapp
