# This workflow requires the environment production with the secrets used in the deploy-azure-aks.yml

name: Deploy Redis to Production

on:
  push:
    branches:
      - production/redis
    tags:
      - 'redis/[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-redis:
    uses: ./.github/workflows/deploy-azure-aks.yml
    with:
      environment: "production"
      services: "redis"
    secrets: inherit
