# This workflow requires the environment production with the secrets used in the deploy-azure-aks.yml

name: Deploy Api to Production

on:
  push:
    branches:
      - production/api
    tags:
      - 'api/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution: "Deve.Api.slnx"

  deploy-aks-api:
    if: ${{ vars.DEPLOY_TYPE == 'aks' }}
    needs: build-and-test
    uses: ./.github/workflows/deploy-azure-aks.yml
    with:
      environment: "production"
      services: "api"
    secrets: inherit

  deploy-app-api:
    if: ${{ vars.DEPLOY_TYPE == 'api' }}
    needs: build-and-test
    uses: ./.github/workflows/deploy-azure-app.yml
    with:
      environment: "production"
      project: "Api/Deve.Api.csproj"
      name: "API"
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
